sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t systtek/docker-reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true systtek/docker-reactapp npm run test -- --coverage

